spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/db_academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
  username: postgres
  password: root
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update

